### ISSUE TITLE
al buscar info de una carpeta cuyo nombre tiene espacios da error

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/fast-devel-server#5]
Para reproducirlo: 
1. crear una carpeta con un espacio como hermana de donde se clonó `fast-devel-server`
2. correr `npm start`
3. en el navegador poner `localhost:54321/auto`
4. ver en la consola el error.

Con hermana me refiero a algo así:

``` sh
mkdir aca
cd aca
mkdir "con espacio"
git clone https://github.com/codenautas/fast-devel-server.git
cd fast-devel-server
npm install
npm start
```

**Comment by diegoefe** [comment]
El problema es que se le está pasando, tanto a dir-info como a qa-control (proveedores), un path codificado para URIs.
La pregunta es: quién preferís que realice la decodificación de la URI, fast-devel-server o sus proveedores?

**Comment by emilioplatzer** [comment]
Acá. Dado que dir-info recibe un path (o un nombre de carpeta) y `fast-devel-server` es el que entiende que un URL se refiere a una carpeta.
